/home/airsim/gym-airsim/environments.py:273: UserWarning: 'gym-semisub-position-aereo-rgb' is not a legal ROS base name. This may cause problems with other ROS tools.
  rospy.init_node(node)
Traceback (most recent call last):
  File "exec.py", line 62, in <module>
    env = gym.make('gym-airsim/hybrid-position-nbv', ip=ip, config=env_config)
  File "/home/airsim/.local/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/airsim/gym-airsim/environments.py", line 276, in __init__
    self.vehicle, self.shadow = self.vs_start(ip, config)
  File "/home/airsim/gym-airsim/environments.py", line 219, in vs_start
    vehicle = ActPosition(ip,
  File "/home/airsim/gym-airsim/airsim-helper/ros_helper.py", line 461, in __init__
    super().__init__(ip, vehicle_name, camera_name, image_dim, camera_fov, global_pose, start_pose, observation_type)
  File "/home/airsim/gym-airsim/airsim-helper/ros_helper.py", line 205, in __init__
    self.confirmConnection()
  File "/home/airsim/gym-airsim/airsim-helper/airsim_base/client.py", line 139, in confirmConnection
    if self.ping():
  File "/home/airsim/gym-airsim/airsim-helper/airsim_base/client.py", line 35, in ping
    return self.client.call('ping')
  File "/home/airsim/.local/lib/python3.8/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/airsim/.local/lib/python3.8/site-packages/msgpackrpc/future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit
Traceback (most recent call last):
  File "exec.py", line 62, in <module>
    env = gym.make('gym-airsim/hybrid-position-nbv', ip=ip, config=env_config)
  File "/home/airsim/.local/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/airsim/gym-airsim/environments.py", line 276, in __init__
    self.vehicle, self.shadow = self.vs_start(ip, config)
  File "/home/airsim/gym-airsim/environments.py", line 219, in vs_start
    vehicle = ActPosition(ip,
  File "/home/airsim/gym-airsim/airsim-helper/ros_helper.py", line 461, in __init__
    super().__init__(ip, vehicle_name, camera_name, image_dim, camera_fov, global_pose, start_pose, observation_type)
  File "/home/airsim/gym-airsim/airsim-helper/ros_helper.py", line 205, in __init__
    self.confirmConnection()
  File "/home/airsim/gym-airsim/airsim-helper/airsim_base/client.py", line 139, in confirmConnection
    if self.ping():
  File "/home/airsim/gym-airsim/airsim-helper/airsim_base/client.py", line 35, in ping
    return self.client.call('ping')
  File "/home/airsim/.local/lib/python3.8/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/airsim/.local/lib/python3.8/site-packages/msgpackrpc/future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit